
import './globals.css'
import { Cairo } from 'next/font/google'
import Footer from '@/components/Footer/Page'
import Header from '@/components/Header/Page'

const cairo = Cairo({ 
  subsets: ['arabic'], 
  weight: ['400', '500','600', '700', '800', '900'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
